sudo: required
dist: trusty
language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - master
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: QFjS+JnHIoDnckrYOXG3QJ6YO03ciZFWk4hrPuLj4/jvz0eTisw81pOPVTu7TpgNOg/iysNCYoPf46Zf+briDEUJR5nJ5+6FUKMB98LjPJewl+2hfQH6pCuU15TF/OuBZ2n8a82TQRM8EFXzomH+oH/ZztTd/JnMdpQpIUcHVqc3ccjMQ/MO7AXF92qi8T3soI/ycX2adBxzSBm171Zt0vjo7DbNy5ScrkVnnF/pTNVgwrcgeXHSoemBeyZxU1j41ZHuREATwCJ7bbtXfLJByGPKfOHBn2+Vg+uiYAofgmz/xgAG+wnxgnTPZxX9K9kz6yi40uHOSHlQPjrJToxsE2NmAEM6jj7QkuYp8fg23tqSot36RHDCQ2yZ4LXgZQbFa82UxeKgjDdkQLmQFwy57bXvG51CKt/QQPHAeTv2PHqJzaOiA1/QPr3srIx0Emnbz+vutt89lC52SDeW41bQqQqgsN6rfwio3gQ9D4F395cbB2byRr0p8jxYzfOiNQMFcdFskedvWez0FTCp7pdVVfEpf02XGTQGyfST3L4PIHC2obRY51k0LEPyZ5ad0lBLtfJFdVyTiNoJHPrW5GuEyWDH26v+idE94Noy+WhTzymTivLFuqhWMBAqfASffARbEmf1edmBtAI4QGaktV2PDgPTE2AjvdDbTXDOn0KWM1I=
install: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -DskipTests=false clean deploy
  --settings .m2/travis-settings.xml"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -DskipTests=true clean --settings
  .m2/travis-settings.xml"
env:
  global:
  - CEDAR_HOST=metadatacenter.orgx
  - CEDAR_NEO4J_HOST=127.0.0.1
  - CEDAR_NEO4J_BOLT_PORT=7687
  - CEDAR_MONGO_APP_USER_NAME=cedarUser
  - CEDAR_MONGO_APP_USER_PASSWORD=password
  - CEDAR_OPENVIEW_HTTP_PORT=9013
  - CEDAR_OPENVIEW_ADMIN_PORT=9113
  - CEDAR_OPENVIEW_STOP_PORT=9213
  - secure: TS8xVQLSJI1b2BVabCsreySHdJincdRAm7KJcO6zzUPxdROb+FtdIUTCaTr5MINgwiBrdECYjh54/0YuLCeosM8RJIkFbzepSq8gcs+EQMlVFGwDKe6vArDMcGMMHeG34atRWAPa9ydCWtomVT0jiefzscdx8ECo4rBlxiTgQh+g9SN01r9MogHcvkhT08Pz8Xfw1jhsBDT7xjjWQfxoTrq5sO5TFFVOA8BcKJdW3xFZ/Sb2Dsq26fHBBTKm8j2orewcomX9tb/ObuAeYoaJ92gVxgezjDGDy1OjKVpVGMxibVH7cQ5wG4OM5nxzBgq4APAWWK2RbVSNIre7txFirfB4nRgHZMqDp17X/4Rl0/HKMLh7GvFY5pSYbzye0w5/kQpkgVg4qq8bkyCDoLjZIiTaxDxCJ9lvwPnjzLN2T6H69kFWLFer/TMNs4SrLHXsxJCJzrli/S5Vm7qDu+DLR/tKwwKtwN/WxTKO1n9T0jmnsmhObAwaZIs+Xm0i9NjcYwrhtCzUEs7oTe0pd5R8/K5iURSX6Rp/6566DtY5hoHbCoKg3x9bVpgTqsliBvKHlZ/i6QV497nAbxFJ804uQJs2MTvw+rb84xeqnQSoJoDxW/i8Bt+yBmJtQXWV55vO+s80HVs3WZB8tFLS8vLpuzmKnqbDxC7nlxf+Gvro7uU=
  - secure: KTNg5ktthEzLygjmgRQkTVS9BfM8teW71kMLrZwAAPRjIlWO3e1i2ykGXrShKo4RYes1KBEh9B2B3PurGrJLWpxO2J/2RyiVEQIQFhoW/mMQV/Oa/M11jqjozcvvrNcn3I6VVbEEXFu6RpTeofZHAvnmm3eeVDPNXfVhQNjO/kcpEQz8ajgOqKB7zOKek8DS4rRiQX66cusglI10UYRjytILFSWZ2cjjNyzOh8bEEgtl1JmExV4/L9mKDGhfg3pqER1P/73oOuuNRHUhJUwE/Q5aVx9DO8P9dL0ZtVTH7hWgJLGIYHf7InK2n2OVLLQwzdnlj6rk1KZAw+L7JeHildqkkGSauRZ807h8Z2uuGmf3y4WzCY52TkQcDwG/ZwUQcBiZICsMlndOKdXQ4rOG8RPbgLqFiIip53Wln+S/q68zNKIHPoerQ95iDAbr7xyQ8hQ7vjcenj8V+XbBWT2ZgKxnQ442iiFU331oi7MKnPh9g0osFvdERQfqUCH8oMPOcQszI9ZknVFb+HhSlxYAAC2N5Egkdz2jo4Y/f6CD1O2HJ9TkXXo3rVMcigimCr0c4WDKIEnf0L+gTpnK12ICHhE55AmslKJbQ8I1GbU2palAhHlDPj+lb5AdPITeAuzkjfFDBoBqfyu75SmoO7O/Z50UCQ0AOxioNp5rQsevFzo=
